import { AssistantToolEntry } from './types';

/**
 * NAVIKO Central Tool Registry
 * Authoritative index of all NAVIKO offline & privacy-first utilities.
 */
export const NAVIKO_TOOLS_REGISTRY: AssistantToolEntry[] = [
  // --- FINANCE ---
  {
    id: 'sip-calculator',
    name: 'SIP & Step-Up Calculator',
    category: 'finance',
    description: 'Calculate mutual fund wealth compounding over 5 to 30 years with optional annual step-up contribution growth.',
    route: '/tools/sip-calculator',
    isPremium: false,
    supportedUseCases: ['Mutual fund investment planning', 'Step-up wealth compounding', 'Long-term goal corpus computation'],
    keywords: ['sip', 'stepup', 'mutual fund', 'compound interest', 'growth', 'wealth', 'investing', 'corpus', 'monthly investment'],
    synonyms: ['calclate sip', 'meri sip', 'sip calculation', 'sip calculator', 'step up sip', 'systematic investment', 'sip grow', 'sip returns'],
  },
  {
    id: 'lump-sum-calculator',
    name: 'Lump Sum Investment Calculator',
    category: 'finance',
    description: 'Calculate expected returns on one-time mutual fund, stock, or index investments with compound interest breakdown.',
    route: '/tools/lump-sum-calculator',
    isPremium: false,
    supportedUseCases: ['One-time mutual fund returns', 'Bonus investment modeling', 'CAGR compounding'],
    keywords: ['lump sum', 'lumpsum', 'one time', 'mutual fund', 'compounding'],
    synonyms: ['one-time investment', 'single deposit', 'lumpsum calculator'],
  },
  {
    id: 'emi-calculator',
    name: 'Loan EMI Calculator',
    category: 'finance',
    description: 'Calculate exact monthly EMI installments, total interest payable, loan-to-interest breakdown, and amortization schedule.',
    route: '/tools/emi-calculator',
    isPremium: false,
    supportedUseCases: ['Home loan EMI', 'Car loan EMI', 'Personal loan interest analysis', 'Monthly installment planning'],
    keywords: ['emi', 'loan', 'home loan', 'car loan', 'personal loan', 'installment', 'interest', 'amortization'],
    synonyms: ['loan emii', 'loan emi', 'loan ki emi', 'calculate emi', 'monthly emi', 'emi calculater', 'emi calculator'],
  },
  {
    id: 'salary-calculator',
    name: 'Salary & In-Hand Tax Calculator',
    category: 'finance',
    description: 'Break down gross CTC into Monthly In-Hand Take-Home, EPF, Professional Tax, and Income Tax with the latest New Tax Regime ₹75,000 standard deduction.',
    route: '/tools/salary-calculator',
    isPremium: false,
    supportedUseCases: ['In-hand monthly take-home salary', 'Income tax slabs breakdown', 'New vs Old tax regime deductions', 'CTC to net pay'],
    keywords: ['salary', 'in hand', 'take home', 'ctc', 'income tax', 'tax slab', 'new tax regime', 'epf', 'tds'],
    synonyms: ['help with tax', 'tax calculater', 'tax calculator', 'tax kitna lagega', 'in hand salary', 'ctc breakdown', 'take home salary'],
  },
  {
    id: 'gst-calculator',
    name: 'GST Calculator',
    category: 'finance',
    description: 'Compute GST (5%, 12%, 18%, 28%) for both GST-Exclusive and GST-Inclusive pricing with CGST, SGST, and IGST breakdown.',
    route: '/tools/gst-calculator',
    isPremium: false,
    supportedUseCases: ['GST inclusive and exclusive billing', 'Tax slab separation', 'Invoice tax checking'],
    keywords: ['gst', 'tax', 'cgst', 'sgst', 'igst', 'invoice', 'exclusive', 'inclusive'],
    synonyms: ['gst calculation', 'gst calculator', 'gst rate', '18% gst'],
  },
  {
    id: 'cagr-calculator',
    name: 'CAGR Calculator',
    category: 'finance',
    description: 'Calculate Compound Annual Growth Rate of any investment or portfolio over any time horizon.',
    route: '/tools/cagr-calculator',
    isPremium: false,
    supportedUseCases: ['Annualized return calculation', 'Stock performance assessment'],
    keywords: ['cagr', 'compound annual growth', 'annual return', 'portfolio growth'],
    synonyms: ['cagr calculator', 'growth rate'],
  },
  {
    id: 'fd-calculator',
    name: 'Fixed Deposit (FD) Calculator',
    category: 'finance',
    description: 'Calculate bank FD maturity amounts, quarterly compounding returns, and total interest for general and senior citizens.',
    route: '/tools/fd-calculator',
    isPremium: false,
    supportedUseCases: ['Bank FD maturity projection', 'Senior citizen interest bonus', 'Term deposit calculation'],
    keywords: ['fd', 'fixed deposit', 'bank fd', 'maturity amount', 'term deposit'],
    synonyms: ['fd calculator', 'fixed deposit calculator', 'bank deposit'],
  },
  {
    id: 'fire-calculator',
    name: 'FIRE (Financial Independence, Retire Early) Calculator',
    category: 'finance',
    description: 'Model your target early retirement corpus using the 4% Safe Withdrawal Rule and savings rate projections.',
    route: '/tools/fire-calculator',
    isPremium: false,
    supportedUseCases: ['Early retirement corpus calculation', 'Safe withdrawal rate analysis', 'Financial freedom timeline'],
    keywords: ['fire', 'retire early', 'financial independence', '4 percent rule', 'retirement corpus'],
    synonyms: ['fire calculator', 'early retirement'],
  },
  {
    id: 'inflation-calculator',
    name: 'Inflation Calculator',
    category: 'finance',
    description: 'Estimate how inflation erodes purchasing power over time and calculate future expenses.',
    route: '/tools/inflation-calculator',
    isPremium: false,
    supportedUseCases: ['Future purchasing power modeling', 'Price rise projection'],
    keywords: ['inflation', 'purchasing power', 'future value', 'cost of living'],
    synonyms: ['inflation calculator', 'future rupee value'],
  },
  {
    id: 'debt-clock',
    name: 'Government Debt Estimator & Clock',
    category: 'finance',
    description: 'Live real-time mathematical estimation of Central Government liabilities, GDP ratio, and debt equivalent per citizen.',
    route: '/tools/debt-clock',
    isPremium: false,
    supportedUseCases: ['Public debt awareness', 'Government borrowing rate tracking'],
    keywords: ['debt', 'national debt', 'debt clock', 'india debt', 'public debt', 'gdp ratio'],
    synonyms: ['debt clock', 'government debt'],
  },
  {
    id: 'budget-calculator',
    name: '50/30/20 Budget Calculator',
    category: 'finance',
    description: 'Divide your monthly net income into Needs (50%), Wants (30%), and Savings (20%) with customized budget allocations.',
    route: '/tools/budget-calculator',
    isPremium: false,
    supportedUseCases: ['Monthly income budgeting', 'Expense segregation', 'Savings discipline'],
    keywords: ['budget', '50 30 20', '50/30/20', 'spending', 'savings', 'expenses'],
    synonyms: ['budget calculator', 'budget planner', '50 30 20 rule'],
  },
  {
    id: 'discount-calculator',
    name: 'Discount & Sale Price Calculator',
    category: 'calculators',
    description: 'Calculate final prices, savings, and stacked percentage discounts for retail purchases and sales.',
    route: '/tools/discount-calculator',
    isPremium: false,
    supportedUseCases: ['Retail sale savings', 'Percentage discount', 'Stacked coupons'],
    keywords: ['discount', 'sale', 'percentage off', 'savings', 'deal'],
    synonyms: ['discount calculator', 'discunt', 'percent off', 'discount kitna hoga'],
  },
  {
    id: 'simple-interest-calculator',
    name: 'Simple Interest Calculator',
    category: 'finance',
    description: 'Calculate basic loan and deposit interest using SI = (P × R × T) / 100.',
    route: '/tools/simple-interest-calculator',
    isPremium: false,
    supportedUseCases: ['Basic loan interest', 'Academic simple interest problems'],
    keywords: ['simple interest', 'si', 'principal', 'interest rate'],
    synonyms: ['si calculator', 'simple interest calculator'],
  },
  {
    id: 'compound-interest-calculator',
    name: 'Compound Interest Calculator',
    category: 'finance',
    description: 'Calculate compound interest with monthly, quarterly, semi-annual, and annual compounding periods.',
    route: '/tools/compound-interest-calculator',
    isPremium: false,
    supportedUseCases: ['Compound growth', 'Periodic contributions', 'Interest compounding'],
    keywords: ['compound interest', 'ci', 'compounding frequency', 'growth'],
    synonyms: ['compound interest calculator', 'ci calculator'],
  },

  // --- STUDENT & ACADEMICS ---
  {
    id: 'attendance-calculator',
    name: 'Attendance & Bunk Calculator',
    category: 'student',
    description: 'Calculate current attendance percentage, safe classes you can bunk above 75%, or how many consecutive classes you must attend to recover.',
    route: '/tools/attendance-calculator',
    isPremium: false,
    supportedUseCases: ['Safe bunk calculation', '75% attendance recovery', 'Semester class tracking'],
    keywords: ['attendance', 'bunk', 'skip class', '75 percent', '75%', 'college attendance', 'classes'],
    synonyms: ['attendance calculator', 'bunk calculator', 'attendance calculate karo', 'can i bunk', 'kitni class bunk kar sakte hain'],
  },
  {
    id: 'cgpa-calculator',
    name: 'CGPA to Percentage Calculator',
    category: 'student',
    description: 'Convert CBSE and university 10-point CGPA into percentage using standard 9.5 formula and custom university formulas.',
    route: '/tools/cgpa-calculator',
    isPremium: false,
    supportedUseCases: ['CBSE CGPA to percentage (× 9.5)', 'College grade conversion', 'Marks percentage equivalence'],
    keywords: ['cgpa', 'gpa', 'percentage', 'grade point', 'marks', 'cbse', 'university'],
    synonyms: ['cgpa calculator', 'cgpa to percentage', 'convert cgpa', 'cgpa convert karo'],
  },
  {
    id: 'study-decision-planner',
    name: 'Study Decision Planner',
    category: 'student',
    description: 'Create a realistic, personalized study plan based on exam deadline, target score, available hours, and subject difficulty with instant feasibility scoring.',
    route: '/student-tools/study-decision-planner',
    isPremium: false,
    supportedUseCases: ['Exam strategy planning', 'Daily revision timetable', 'Study hours optimization'],
    keywords: ['study plan', 'study decision', 'exam plan', 'revision schedule', 'exam preparation'],
    synonyms: ['study pln', 'study plan', 'study planner', 'exam schedule', 'padhai ka plan'],
  },
  {
    id: 'backlog-recovery-planner',
    name: 'Backlog Recovery Planner',
    category: 'student',
    description: 'Generate a structured day-by-day recovery roadmap to clear pending syllabus chapters without burnout.',
    route: '/student-tools/backlog-recovery-planner',
    isPremium: false,
    supportedUseCases: ['Clear pending syllabus', 'Exam backlog clearing', 'Subject workload distribution'],
    keywords: ['backlog', 'syllabus backlog', 'pending chapters', 'recover backlog', 'syllabus'],
    synonyms: ['backlog planner', 'syllabus backlog recovery', 'backlog clear kaise kare'],
  },
  {
    id: 'can-i-finish-my-syllabus',
    name: 'Can I Finish My Syllabus? Calculator',
    category: 'student',
    description: 'Instantly check if your available daily study hours are sufficient to complete remaining chapters before your exam date.',
    route: '/student-tools/can-i-finish-my-syllabus',
    isPremium: false,
    supportedUseCases: ['Syllabus feasibility analysis', 'Pacing calculation', 'Study pace buffer evaluation'],
    keywords: ['finish syllabus', 'can i finish', 'syllabus complete', 'study hours', 'exam countdown'],
    synonyms: ['can i finish syllabus', 'syllabus complete hoga kya'],
  },
  {
    id: 'mock-test-analyzer',
    name: 'Mock Test Performance Analyzer',
    category: 'student',
    description: 'Log test scores, visualize score trajectory, analyze negative marking accuracy, and identify weak topics.',
    route: '/student-tools/mock-test-analyzer',
    isPremium: false,
    supportedUseCases: ['Test series score logging', 'Negative marking impact', 'Subject strengths/weaknesses'],
    keywords: ['mock test', 'test series', 'mock score', 'negative marking', 'test accuracy'],
    synonyms: ['mock test analyzer', 'test score analysis'],
  },
  {
    id: 'study-timetable-generator',
    name: 'Study Timetable Generator',
    category: 'student',
    description: 'Generate customized daily and weekly study schedules based on subjects, exam dates, and preferred study hours.',
    route: '/tools/study-timetable-generator',
    isPremium: false,
    supportedUseCases: ['Daily routine generation', 'Weekly subject schedule', 'Pomodoro sessions'],
    keywords: ['timetable', 'study schedule', 'routine', 'study timetable', 'weekly schedule'],
    synonyms: ['timetable generator', 'study timetable', 'time table banao'],
  },
  {
    id: 'typing-speed-test',
    name: 'Typing Speed Test',
    category: 'student',
    description: 'Test your Words Per Minute (WPM), net accuracy, and error rate with timed passages and real-time feedback.',
    route: '/tools/typing-speed-test',
    isPremium: false,
    supportedUseCases: ['Typing speed measurement', 'Accuracy training', 'Competitive exam typing preparation'],
    keywords: ['typing', 'typing speed', 'wpm', 'words per minute', 'accuracy', 'keyboard'],
    synonyms: ['typing test', 'typing speed test', 'check typing speed'],
  },
  {
    id: 'random-question-generator',
    name: 'Random Question Generator',
    category: 'student',
    description: 'Practice interview questions, coding concepts, aptitude, and GK topics categorized by subject.',
    route: '/tools/random-question-generator',
    isPremium: false,
    supportedUseCases: ['Interview prep', 'Aptitude practice', 'Revision flashcards'],
    keywords: ['questions', 'quiz', 'interview question', 'aptitude', 'gk'],
    synonyms: ['question generator', 'practice questions'],
  },

  // --- RESUME & CAREER ---
  {
    id: 'resume-builder',
    name: 'ATS-Friendly Resume Builder',
    category: 'career',
    description: 'Build clean, professional, single-column resumes engineered to pass automated Applicant Tracking Systems with instant PDF export.',
    route: '/tools/resume-builder',
    isPremium: false,
    supportedUseCases: ['ATS resume creation', 'Student and fresher CV', 'Job application resume formatting', 'Clean PDF resume export'],
    keywords: ['resume', 'cv', 'ats resume', 'resume builder', 'curriculum vitae', 'job application', 'fresher resume'],
    synonyms: ['make resume', 'resum', 'resume banana hai', 'resume ke liye help', 'build resume', 'cv builder', 'ats cv'],
  },

  // --- PDF TOOLS ---
  {
    id: 'pdf-compressor',
    name: 'PDF Compressor',
    category: 'pdf',
    description: 'Reduce PDF file size for emails, government portals, and college admissions while preserving readability. 100% browser-based.',
    route: '/tools/pdf-compressor',
    isPremium: false,
    supportedUseCases: ['Reduce PDF file size', 'Compress for job applications/exams', 'Email attachment optimization'],
    keywords: ['compress pdf', 'reduce pdf', 'shrink pdf', 'pdf size', 'pdf kb', 'small pdf'],
    synonyms: ['pdf comprse', 'compress pdf', 'pdf ka size kam karna hai', 'pdf reduce', 'pdf shrink'],
  },
  {
    id: 'pdf-merge',
    name: 'PDF Merge',
    category: 'pdf',
    description: 'Combine multiple PDF files into a single organized document in your custom order with zero server uploads.',
    route: '/tools/pdf-merge',
    isPremium: false,
    supportedUseCases: ['Combine multiple documents', 'Merge scanned pages', 'Bind certificates and marksheets'],
    keywords: ['merge pdf', 'combine pdf', 'join pdf', 'bind pdf', 'multiple pdf'],
    synonyms: ['merge pdfs', 'combine pdf files', 'pdf jodo'],
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF Converter',
    category: 'pdf',
    description: 'Convert photos, scans, and PNG/JPG images into formatted A4 or Letter PDF documents with custom margins.',
    route: '/tools/jpg-to-pdf',
    isPremium: false,
    supportedUseCases: ['Photos to document', 'Assignment image to PDF', 'Marksheet scan to PDF'],
    keywords: ['jpg to pdf', 'image to pdf', 'png to pdf', 'photo to pdf', 'convert to pdf'],
    synonyms: ['image to pdf converter', 'photo to pdf convert'],
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG Converter',
    category: 'pdf',
    description: 'Extract and convert every page of a PDF document into high-resolution JPG or PNG images with 1-click ZIP download.',
    route: '/tools/pdf-to-jpg',
    isPremium: false,
    supportedUseCases: ['Extract pages as images', 'Convert document pages to pictures'],
    keywords: ['pdf to jpg', 'pdf to image', 'pdf to png', 'extract pages', 'export images'],
    synonyms: ['pdf to image converter', 'extract images from pdf'],
  },
  {
    id: 'pdf-split',
    name: 'PDF Split Tool',
    category: 'pdf',
    description: 'Extract specific page ranges (e.g. 1-3, 5) or separate a large PDF into individual single-page documents.',
    route: '/tools/pdf-split',
    isPremium: false,
    supportedUseCases: ['Extract specific pages', 'Remove unwanted pages', 'Divide large PDFs'],
    keywords: ['split pdf', 'separate pdf', 'cut pdf', 'extract pages'],
    synonyms: ['pdf splitter', 'split pdf document'],
  },

  // --- IMAGE TOOLS ---
  {
    id: 'background-remover',
    name: 'Background Remover',
    category: 'image',
    description: 'Remove solid photo backgrounds, isolate product shots and signatures, and export transparent PNGs right in your browser.',
    route: '/tools/background-remover',
    isPremium: false,
    supportedUseCases: ['Transparent PNG creation', 'Signature background removal', 'Product photo cutout'],
    keywords: ['background remover', 'remove background', 'bg remover', 'transparent', 'cutout'],
    synonyms: ['remove bg', 'background remove karo', 'transparent background'],
  },
  {
    id: 'image-cropper',
    name: 'Image Cropper',
    category: 'image',
    description: 'Crop photos with standard aspect ratio presets (1:1 Square, 16:9, 4:3, 3:2, and Indian Passport Photo 3.5×4.5 cm).',
    route: '/tools/image-cropper',
    isPremium: false,
    supportedUseCases: ['Passport photo sizing', 'Social media cropping', 'Image framing'],
    keywords: ['crop', 'image cropper', 'passport photo crop', 'aspect ratio'],
    synonyms: ['crop image', 'photo crop karo', 'passport size photo'],
  },
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    category: 'image',
    description: 'Compress JPG, PNG, and WebP images down to exact KB targets (e.g. under 20KB or 50KB for government portals).',
    route: '/tools/image-compressor',
    isPremium: false,
    supportedUseCases: ['Image under 50KB for portals', 'Web image size reduction', 'Fast loading photos'],
    keywords: ['compress image', 'reduce image size', 'photo kb', 'image under 50kb'],
    synonyms: ['image compressor', 'photo compress', 'image size kam karo'],
  },
  {
    id: 'image-resizer',
    name: 'Image Resizer',
    category: 'image',
    description: 'Scale image dimensions in pixels or percentage with aspect ratio lock and multi-format export.',
    route: '/tools/image-resizer',
    isPremium: false,
    supportedUseCases: ['Change pixel dimensions', 'Resize for form uploads'],
    keywords: ['resize image', 'image dimensions', 'scale photo', 'width height'],
    synonyms: ['image resizer', 'photo resize'],
  },
  {
    id: 'jpg-to-png',
    name: 'JPG to PNG Converter',
    category: 'image',
    description: 'Convert JPEG photos to high-quality lossless PNG format with optional background transparency.',
    route: '/tools/jpg-to-png',
    isPremium: false,
    supportedUseCases: ['Convert JPEG to PNG', 'Lossless image export'],
    keywords: ['jpg to png', 'jpeg to png', 'format conversion'],
    synonyms: ['jpg to png converter'],
  },
  {
    id: 'png-to-jpg',
    name: 'PNG to JPG Converter',
    category: 'image',
    description: 'Convert PNG graphics and screenshots to lightweight JPG images with custom background canvas fill.',
    route: '/tools/png-to-jpg',
    isPremium: false,
    supportedUseCases: ['Convert transparent PNG to JPG', 'Reduce PNG file size to JPG'],
    keywords: ['png to jpg', 'png to jpeg', 'screenshot to jpg'],
    synonyms: ['png to jpg converter'],
  },

  // --- HEALTH & FITNESS ---
  {
    id: 'bmi-calculator',
    name: 'BMI Calculator',
    category: 'health',
    description: 'Calculate Body Mass Index, healthy weight range, and WHO weight categories using height (cm/ft) and weight (kg/lbs).',
    route: '/tools/bmi-calculator',
    isPremium: false,
    supportedUseCases: ['Check healthy weight', 'Body Mass Index calculation', 'Fitness target weight'],
    keywords: ['bmi', 'body mass index', 'weight', 'height', 'fitness', 'obesity', 'underweight', 'ideal weight'],
    synonyms: ['bmi calculate', 'bmi calculator', 'bmi', 'check bmi', 'mera bmi kitna hai', 'height weight calculator'],
  },
  {
    id: 'diet-plan-manager',
    name: 'Diet Plan Manager',
    category: 'health',
    description: 'Create customized 7-day meal plans, calculate calorie deficits/surpluses, and generate smart grocery shopping lists.',
    route: '/tools/diet-plan-manager',
    isPremium: true,
    supportedUseCases: ['7-day meal planning', 'Calorie surplus/deficit calculation', 'Grocery list export'],
    keywords: ['diet', 'meal plan', 'nutrition', 'calories', 'weight loss', 'muscle gain', 'grocery'],
    synonyms: ['diet plan', 'meal planner', 'diet plan manager'],
  },
  {
    id: 'nutrition',
    name: 'Nutrition & Macro Food Tracker',
    category: 'health',
    description: 'Look up calorie, protein, carb, fat, and fiber content across 100+ foods with daily macro balance breakdowns.',
    route: '/tools/nutrition',
    isPremium: false,
    supportedUseCases: ['Food calorie lookup', 'Protein content check', 'Macro breakdown'],
    keywords: ['nutrition', 'calories', 'protein', 'carbs', 'macros', 'food database'],
    synonyms: ['food nutrition', 'calories tracker', 'protein calculator'],
  },

  // --- MATHEMATICAL & PRODUCTIVITY ---
  {
    id: 'number-calculator',
    name: 'Standard Number Calculator',
    category: 'calculators',
    description: 'High-precision standard calculator with arithmetic operations, memory registers (M+, M-), and history tape.',
    route: '/tools/number-calculator',
    isPremium: false,
    supportedUseCases: ['Standard everyday math', 'Calculation history tracking', 'Keyboard number input'],
    keywords: ['calculator', 'basic calculator', 'math', 'arithmetic', 'addition', 'subtraction'],
    synonyms: ['calclutor', 'calculator', 'math calculator', 'number calculator'],
  },
  {
    id: 'scientific-calculator',
    name: 'Scientific Calculator',
    category: 'calculators',
    description: 'Scientific calculator supporting Trigonometry (sin, cos, tan), Logarithms (ln, log), Roots, Powers, and DEG/RAD modes.',
    route: '/tools/scientific-calculator',
    isPremium: false,
    supportedUseCases: ['Trigonometry', 'Logarithms', 'Exponential and powers', 'Engineering mathematics'],
    keywords: ['scientific calculator', 'trigonometry', 'sin', 'cos', 'tan', 'log', 'ln', 'roots', 'radian'],
    synonyms: ['scientific calc', 'trig calculator'],
  },
  {
    id: 'percentage-calculator',
    name: 'Percentage Calculator',
    category: 'calculators',
    description: 'Solve percentage questions: "What is X% of Y?", percentage increase/decrease, and discount ratios.',
    route: '/tools/percentage-calculator',
    isPremium: false,
    supportedUseCases: ['Percentage of number', 'Percentage increase/decrease', 'Ratio to percentage'],
    keywords: ['percentage', 'percent', 'ratio', 'fraction to percent'],
    synonyms: ['percentage calculator', 'percent calculator', 'percent calculate karo'],
  },
  {
    id: 'age-calculator',
    name: 'Age & Birthday Calculator',
    category: 'calculators',
    description: 'Find exact age in years, months, and days, live countdown to next birthday, and total days lived.',
    route: '/tools/age-calculator',
    isPremium: false,
    supportedUseCases: ['Exact age calculation', 'Birthday countdown', 'Government exam age eligibility check'],
    keywords: ['age', 'birthday', 'dob', 'how old', 'date of birth', 'age eligibility'],
    synonyms: ['age calculator', 'meri age kitni hai', 'calculate age'],
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    category: 'calculators',
    description: 'Convert length, weight, temperature, speed, area, and digital storage units with instant bidirectional calculation.',
    route: '/tools/unit-converter',
    isPremium: false,
    supportedUseCases: ['KM to Miles', 'KG to Pounds', 'Celsius to Fahrenheit', 'GB to MB'],
    keywords: ['unit converter', 'units', 'convert', 'km to miles', 'kg to lbs', 'temperature'],
    synonyms: ['unit conversion', 'converter'],
  },
  {
    id: 'word-counter',
    name: 'Word Counter & Text Analyzer',
    category: 'productivity',
    description: 'Count words, characters, sentences, and estimated reading/speaking time with keyword density analysis.',
    route: '/tools/word-counter',
    isPremium: false,
    supportedUseCases: ['Essay word limit check', 'Reading time estimate', 'Character count for tweets and applications'],
    keywords: ['word counter', 'character count', 'words', 'reading time', 'text analysis'],
    synonyms: ['count words', 'character counter'],
  },
  {
    id: 'qr-code-generator',
    name: 'QR Code Generator',
    category: 'productivity',
    description: 'Generate customizable QR codes for URLs, WiFi networks, contact cards (vCard), emails, and text with PNG/SVG export.',
    route: '/tools/qr-code-generator',
    isPremium: false,
    supportedUseCases: ['Website URL QR', 'WiFi password sharing QR', 'Contact vCard QR'],
    keywords: ['qr code', 'generate qr', 'create qr', 'wifi qr', 'qr code generator'],
    synonyms: ['qr generator', 'make qr code'],
  },
];

/**
 * Hub Category Routes
 */
export const CATEGORY_HUBS: Record<string, { name: string; route: string; description: string }> = {
  finance: {
    name: 'Finance Tools Hub',
    route: '/finance-tools',
    description: '14+ calculators for SIP, EMI, Salary In-Hand, GST, FD, FIRE, and Debt Clock.',
  },
  student: {
    name: 'Student Tools Hub',
    route: '/student-tools',
    description: 'Study Decision Planner, Attendance Calculator, CGPA to %, Backlog Planner, and Mock Test Analyzer.',
  },
  pdf: {
    name: 'PDF Utilities Suite',
    route: '/pdf-tools',
    description: 'Merge, Compress, JPG to PDF, PDF to JPG, and Split PDF tools running 100% in browser.',
  },
  image: {
    name: 'Image Utilities Suite',
    route: '/image-tools',
    description: 'Background Remover, Cropper, Exact KB Compressor, and Format Converters.',
  },
  calculators: {
    name: 'Calculators Hub',
    route: '/calculators',
    description: 'Standard, Scientific, Percentage, Age, and Discount calculators.',
  },
  health: {
    name: 'Health & Fitness Hub',
    route: '/health-tools',
    description: 'BMI Calculator, 7-day Diet Plan Manager, and Macro Food Nutrition Tracker.',
  },
  all: {
    name: 'All Tools Directory',
    route: '/all-tools',
    description: 'Browse the complete index of 46+ fast, private NAVIKO tools.',
  },
  premium: {
    name: 'NAVIKO Premium Plans',
    route: '/premium',
    description: '₹1 7-Day Trial, NAVIKO Plus, and NAVIKO Pro with expanded limits and ad-free experience.',
  },
};
